---
name: Lint

'on':
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    python_lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: psf/black@stable
              with:
                black_args: ". --line-length 120 --check --diff"
